// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/capture-order': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/capture-order.post').default>>>>
    }
    '/api/create-order': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/create-order.post').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/@nuxt+nitro-server@3.21.2_db0@0.3.4_ioredis@5.10.0_magicast@0.5.2_nuxt@3.21.2_@parcel+w_7775f3499a3a49de1df47bee25f090a1/node_modules/@nuxt/nitro-server/dist/runtime/handlers/renderer').default>>>>
    }
    '/__nuxt_island/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/#internal/nuxt/island-renderer').default>>>>
    }
  }
}
export {}